#include "SCCDataArguments.hpp"
#include "SCCDataContentOfAddress.hpp"
#include "SCCDataNumericLiteral.hpp"
#include "SCCDataStackVariable.hpp"
#include "SCCDataStaticVariable.hpp"
#include "SCCDataStringLiteral.hpp"
#include "SCCDataTempValue.hpp"
#include "SCCDataWrapper.hpp"